### ISSUE TITLE
Rinex Observation File Epoch Issue

### ISSUE THREAD

**Issue by libiliby88** [gnss-sdr/gnss-sdr#113]
Hi,

I want to use the output RINEX file from GNSS-SDR to do some postprocess. I was running realtime with USRP front-end with the example configuration file. I found that the RINEX observation files are not logging at the integer epochs like most other commercial receivers do. And once the receiver lose lock the epoch time start at arbitrary instant, not following the sampling rate that is set in the configuration file. In my opinion, once the receiver lose lock, it should skip this sample and recover logging at next time following the sampling configuration.

Is it possible to make it log RINEX obsevations at integer seconds ? 
Is it possible to make the logging following the sampling rate exactly?

Bingxuan

**Comment by carlesfernandez** [comment]
The RINEX logging at integer seconds should now be fixed in the `next` branch. Two new parameters have been exposed to the configuration: `rinexobs_rate_ms` (which defaults to 1000 ms) sets the rate at which the observations are logged in the RINEX observation file, and `rinexnav_rate_ms` (which defaults to 6000 ms) sets the rate at which the navigation message parameters are logged in the RINEX navigation file. This has been documented in https://gnss-sdr.org/docs/sp-blocks/pvt/#implementation-rtklib_pvt 

The RINEX logging should now recover from a loss of lock and annotate data correctly.

I'm closing this issue, please feel free to open a new one if other problems arise.
