### ISSUE TITLE
Central frequency for GLONASS L1

### ISSUE THREAD

**Issue by rommar** [gnss-sdr/gnss-sdr#245]
[Documentation for channels block](https://gnss-sdr.org/docs/sp-blocks/channels/) says central frequency for Glonass L1 is 1.57542 GHz. Is that really correct? At the same time [readme page](https://github.com/gnss-sdr/gnss-sdr/blob/master/README.md) states Glonass L1 is centered at 1601.72 MHz. To my knowledge Glonass is centered at 1.602 GHz and satellites broadcast on different frequencies.

I'm using OsmoSDR signal source with Blade-RF frontend. What should I specify as SignalSource.freq parameter? How big should be sampling frequency?

Gnss-sdr version is 0.0.10 from master branch.

**Comment by carlesfernandez** [comment]
Dear @rommar,
you are right on this, those errors were fixed in the [web documentation](https://gnss-sdr.org/docs/sp-blocks/channels/) and the [README.md](https://github.com/gnss-sdr/gnss-sdr/blob/next/README.md). 

The center frequency for GLONASS L1 is 1.602 GHz and shoud be set as:

```
SignalSource.freq=1602000000
```

The minimal sampling frequency should be around 13.5 Msps (passband) or 6.75 Msps (complex baseband). A little bit less can also work:

```
GNSS-SDR.internal_fs_sps=6625000
```

You can check out the GLONASS examples at [conf/](https://github.com/gnss-sdr/gnss-sdr/tree/next/conf)

Hope this helps,
Carles
