### ISSUE TITLE
Two RF Channels

### ISSUE THREAD

**Issue by AgileEngineeringLLC** [gnss-sdr/gnss-sdr#386]
I have a HackRF One and a couple of RTL-SDRs. I'm able to run these in L1-only mode just fine. I can even run the HackRF at 4MS/S with L1!

If I want to track both L1 and L2, do I use a single HackRf or do I need two? I apologize if this is a dumb question, I'm still trying to figure out details about RF front ends. By any chance is there a sample conf file or hints for doing this? 

Thanks for the help, I appreciate it!

**Comment by carlesfernandez** [comment]
Hi Don,

please apologize for my delay in answering. Dual-frequency receiving is tricky with a pair of single-frequency receivers since you need to drive them with the same clock. Both with HackRFs and with RTL-SDRs, it requires a little bit of hardware manipulation. We did it with a couple of RTL-SDR v3, just for the fun, and they worked great! And even in single frequency, you can build up an extremely cheap antenna array :-)
