### ISSUE TITLE
GNSS-SDR and Internal Monitoring tool installation issues

### ISSUE THREAD

**Issue by cipriancircu** [gnss-sdr/gnss-sdr#703]
Hello,

I'm trying to re-install GNSS-SDR on a machine on which it worked before. Currently, this is the issue that I encounter (see image that has 1 on it).
![1](https://user-images.githubusercontent.com/47553433/213195932-b07f9c6d-d2b7-46fa-a352-d8e570ec29b5.PNG)
Also, when trying to re-install the internal monitoring tool the issue that I encounter is presented in image 2.
![2](https://user-images.githubusercontent.com/47553433/213195940-67e979db-7069-4d22-99f0-5b505cc91060.PNG)

I have tried to install these tools with all the methods presented on the gnss-sdr website and no method works. Also, I have looked up the errors online and I could not find anything helpful.

Please let me know what approach should I take on this issue.

Thank you!

**Comment by jwmelto** [comment]
The approach you should take is to follow basic debugging principles. First, read the error messages. They very often have useful information in solving your problem. In the case of your first image, GNU Radio didn't build. This means that you don't have a working GNU Radio installed and GNSS-SDR tried to help you out, but you are missing some dependencies.

You provide no information on your operating system, installed software versions, command line, etc. Your entire build log is needed for anyone to have a clue.

The second image is an annoying protobuf version incompatibility issue. See https://github.com/protocolbuffers/protobuf/issues/5868#issuecomment-496490880. I install and build protobuf myself, rather than let GNSS-SDR do it.

Make sure you have a clean build environment (recursively delete all the files under **build**.
