### ISSUE TITLE
Initial values for Pseudorange

### ISSUE THREAD

**Issue by JohnNatHaysys** [gnss-sdr/gnss-sdr#765]
My reading of the GNS-SDR documentation suggests that the nearest satellite is set to a pseudorange corresponding to 68.802ms delay. Using gnss-sdr-monitor it is clear that the values for each satellite pseudorange are random, varying from a few thousand metres to a few thousand kilometres. Only when the RTKLIB_PVT implementation has derived a position does the pseudorange match the expected distance of around 25,000km

There is a message passed from the PVT to the Hybrid_Observables but I would like this to be something sensible and fixed. Any suggestions as to how to implement this.

Ultimately I would like to replace the RTKLIB_PVT with a custom implementation which allows for 'satellites' to be  - for example - drones covering a moderate area, but allowing a receiver to calculate position.

**Comment by carlesfernandez** [comment]
Thank you for your question. It is possible to change the internal PVT solver (RTKLIB_PVT) with your custom function. Regarding the time offset message from PVT to Hybrid obs, I am afraid you will still need to pass this message because in a TDOA system, you need to compute the common offset in the time of arrivals with respect to the satellite /drone time.
